//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OperationsPortal.NAVWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Operations_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Operations")]
    public partial class Operations : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckCustomerLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckValidCustomerNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateReleaseOrderReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateWarehouseReceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCMAProductLedgerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientContractsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContractPartiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContractProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContractStorageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerContractDispatchOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerContractReceiptOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerContractReleaseOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerContractTransferOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerProfileDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomerAutoGenPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomerPasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Operations() {
            this.Url = global::OperationsPortal.Properties.Settings.Default.OperationsPortal_NAVWS_Operations;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckCustomerLoginCompletedEventHandler CheckCustomerLoginCompleted;
        
        /// <remarks/>
        public event CheckValidCustomerNoCompletedEventHandler CheckValidCustomerNoCompleted;
        
        /// <remarks/>
        public event GenerateReleaseOrderReportCompletedEventHandler GenerateReleaseOrderReportCompleted;
        
        /// <remarks/>
        public event GenerateWarehouseReceiptCompletedEventHandler GenerateWarehouseReceiptCompleted;
        
        /// <remarks/>
        public event GetCMAProductLedgerCompletedEventHandler GetCMAProductLedgerCompleted;
        
        /// <remarks/>
        public event GetClientContractsCompletedEventHandler GetClientContractsCompleted;
        
        /// <remarks/>
        public event GetContractPartiesCompletedEventHandler GetContractPartiesCompleted;
        
        /// <remarks/>
        public event GetContractProductsCompletedEventHandler GetContractProductsCompleted;
        
        /// <remarks/>
        public event GetContractStorageCompletedEventHandler GetContractStorageCompleted;
        
        /// <remarks/>
        public event GetCustomerContractDispatchOrdersCompletedEventHandler GetCustomerContractDispatchOrdersCompleted;
        
        /// <remarks/>
        public event GetCustomerContractReceiptOrdersCompletedEventHandler GetCustomerContractReceiptOrdersCompleted;
        
        /// <remarks/>
        public event GetCustomerContractReleaseOrdersCompletedEventHandler GetCustomerContractReleaseOrdersCompleted;
        
        /// <remarks/>
        public event GetCustomerContractTransferOrdersCompletedEventHandler GetCustomerContractTransferOrdersCompleted;
        
        /// <remarks/>
        public event GetCustomerEmailCompletedEventHandler GetCustomerEmailCompleted;
        
        /// <remarks/>
        public event GetCustomerProfileDetailsCompletedEventHandler GetCustomerProfileDetailsCompleted;
        
        /// <remarks/>
        public event UpdateCustomerAutoGenPasswordCompletedEventHandler UpdateCustomerAutoGenPasswordCompleted;
        
        /// <remarks/>
        public event UpdateCustomerPasswordCompletedEventHandler UpdateCustomerPasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:CheckCustomerLogin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="CheckCustomerLogin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CheckCustomerLogin(string username, string userpassword) {
            object[] results = this.Invoke("CheckCustomerLogin", new object[] {
                        username,
                        userpassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckCustomerLoginAsync(string username, string userpassword) {
            this.CheckCustomerLoginAsync(username, userpassword, null);
        }
        
        /// <remarks/>
        public void CheckCustomerLoginAsync(string username, string userpassword, object userState) {
            if ((this.CheckCustomerLoginOperationCompleted == null)) {
                this.CheckCustomerLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCustomerLoginOperationCompleted);
            }
            this.InvokeAsync("CheckCustomerLogin", new object[] {
                        username,
                        userpassword}, this.CheckCustomerLoginOperationCompleted, userState);
        }
        
        private void OnCheckCustomerLoginOperationCompleted(object arg) {
            if ((this.CheckCustomerLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCustomerLoginCompleted(this, new CheckCustomerLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:CheckValidCustomerNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="CheckValidCustomerNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckValidCustomerNo(string username) {
            object[] results = this.Invoke("CheckValidCustomerNo", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckValidCustomerNoAsync(string username) {
            this.CheckValidCustomerNoAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckValidCustomerNoAsync(string username, object userState) {
            if ((this.CheckValidCustomerNoOperationCompleted == null)) {
                this.CheckValidCustomerNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckValidCustomerNoOperationCompleted);
            }
            this.InvokeAsync("CheckValidCustomerNo", new object[] {
                        username}, this.CheckValidCustomerNoOperationCompleted, userState);
        }
        
        private void OnCheckValidCustomerNoOperationCompleted(object arg) {
            if ((this.CheckValidCustomerNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckValidCustomerNoCompleted(this, new CheckValidCustomerNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GenerateReleaseOrderReport", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GenerateReleaseOrderReport_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateReleaseOrderReport(string path, string fileName, string receiptNo, string contractNo) {
            this.Invoke("GenerateReleaseOrderReport", new object[] {
                        path,
                        fileName,
                        receiptNo,
                        contractNo});
        }
        
        /// <remarks/>
        public void GenerateReleaseOrderReportAsync(string path, string fileName, string receiptNo, string contractNo) {
            this.GenerateReleaseOrderReportAsync(path, fileName, receiptNo, contractNo, null);
        }
        
        /// <remarks/>
        public void GenerateReleaseOrderReportAsync(string path, string fileName, string receiptNo, string contractNo, object userState) {
            if ((this.GenerateReleaseOrderReportOperationCompleted == null)) {
                this.GenerateReleaseOrderReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateReleaseOrderReportOperationCompleted);
            }
            this.InvokeAsync("GenerateReleaseOrderReport", new object[] {
                        path,
                        fileName,
                        receiptNo,
                        contractNo}, this.GenerateReleaseOrderReportOperationCompleted, userState);
        }
        
        private void OnGenerateReleaseOrderReportOperationCompleted(object arg) {
            if ((this.GenerateReleaseOrderReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateReleaseOrderReportCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GenerateWarehouseReceipt", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GenerateWarehouseReceipt_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateWarehouseReceipt(string path, string fileName, string receiptNo, string contractNo) {
            this.Invoke("GenerateWarehouseReceipt", new object[] {
                        path,
                        fileName,
                        receiptNo,
                        contractNo});
        }
        
        /// <remarks/>
        public void GenerateWarehouseReceiptAsync(string path, string fileName, string receiptNo, string contractNo) {
            this.GenerateWarehouseReceiptAsync(path, fileName, receiptNo, contractNo, null);
        }
        
        /// <remarks/>
        public void GenerateWarehouseReceiptAsync(string path, string fileName, string receiptNo, string contractNo, object userState) {
            if ((this.GenerateWarehouseReceiptOperationCompleted == null)) {
                this.GenerateWarehouseReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateWarehouseReceiptOperationCompleted);
            }
            this.InvokeAsync("GenerateWarehouseReceipt", new object[] {
                        path,
                        fileName,
                        receiptNo,
                        contractNo}, this.GenerateWarehouseReceiptOperationCompleted, userState);
        }
        
        private void OnGenerateWarehouseReceiptOperationCompleted(object arg) {
            if ((this.GenerateWarehouseReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateWarehouseReceiptCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCMAProductLedger", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCMAProductLedger_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCMAProductLedger(string contractNo, string productNo) {
            object[] results = this.Invoke("GetCMAProductLedger", new object[] {
                        contractNo,
                        productNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCMAProductLedgerAsync(string contractNo, string productNo) {
            this.GetCMAProductLedgerAsync(contractNo, productNo, null);
        }
        
        /// <remarks/>
        public void GetCMAProductLedgerAsync(string contractNo, string productNo, object userState) {
            if ((this.GetCMAProductLedgerOperationCompleted == null)) {
                this.GetCMAProductLedgerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCMAProductLedgerOperationCompleted);
            }
            this.InvokeAsync("GetCMAProductLedger", new object[] {
                        contractNo,
                        productNo}, this.GetCMAProductLedgerOperationCompleted, userState);
        }
        
        private void OnGetCMAProductLedgerOperationCompleted(object arg) {
            if ((this.GetCMAProductLedgerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCMAProductLedgerCompleted(this, new GetCMAProductLedgerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetClientContracts", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetClientContracts_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetClientContracts(string clientNo) {
            object[] results = this.Invoke("GetClientContracts", new object[] {
                        clientNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientContractsAsync(string clientNo) {
            this.GetClientContractsAsync(clientNo, null);
        }
        
        /// <remarks/>
        public void GetClientContractsAsync(string clientNo, object userState) {
            if ((this.GetClientContractsOperationCompleted == null)) {
                this.GetClientContractsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientContractsOperationCompleted);
            }
            this.InvokeAsync("GetClientContracts", new object[] {
                        clientNo}, this.GetClientContractsOperationCompleted, userState);
        }
        
        private void OnGetClientContractsOperationCompleted(object arg) {
            if ((this.GetClientContractsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientContractsCompleted(this, new GetClientContractsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetContractParties", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetContractParties_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetContractParties(string contractNo) {
            object[] results = this.Invoke("GetContractParties", new object[] {
                        contractNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetContractPartiesAsync(string contractNo) {
            this.GetContractPartiesAsync(contractNo, null);
        }
        
        /// <remarks/>
        public void GetContractPartiesAsync(string contractNo, object userState) {
            if ((this.GetContractPartiesOperationCompleted == null)) {
                this.GetContractPartiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContractPartiesOperationCompleted);
            }
            this.InvokeAsync("GetContractParties", new object[] {
                        contractNo}, this.GetContractPartiesOperationCompleted, userState);
        }
        
        private void OnGetContractPartiesOperationCompleted(object arg) {
            if ((this.GetContractPartiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContractPartiesCompleted(this, new GetContractPartiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetContractProducts", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetContractProducts_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetContractProducts(string contractNo) {
            object[] results = this.Invoke("GetContractProducts", new object[] {
                        contractNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetContractProductsAsync(string contractNo) {
            this.GetContractProductsAsync(contractNo, null);
        }
        
        /// <remarks/>
        public void GetContractProductsAsync(string contractNo, object userState) {
            if ((this.GetContractProductsOperationCompleted == null)) {
                this.GetContractProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContractProductsOperationCompleted);
            }
            this.InvokeAsync("GetContractProducts", new object[] {
                        contractNo}, this.GetContractProductsOperationCompleted, userState);
        }
        
        private void OnGetContractProductsOperationCompleted(object arg) {
            if ((this.GetContractProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContractProductsCompleted(this, new GetContractProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetContractStorage", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetContractStorage_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetContractStorage(string contractNo) {
            object[] results = this.Invoke("GetContractStorage", new object[] {
                        contractNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetContractStorageAsync(string contractNo) {
            this.GetContractStorageAsync(contractNo, null);
        }
        
        /// <remarks/>
        public void GetContractStorageAsync(string contractNo, object userState) {
            if ((this.GetContractStorageOperationCompleted == null)) {
                this.GetContractStorageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContractStorageOperationCompleted);
            }
            this.InvokeAsync("GetContractStorage", new object[] {
                        contractNo}, this.GetContractStorageOperationCompleted, userState);
        }
        
        private void OnGetContractStorageOperationCompleted(object arg) {
            if ((this.GetContractStorageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContractStorageCompleted(this, new GetContractStorageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCustomerContractDispatchOrd" +
            "ers", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCustomerContractDispatchOrders_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCustomerContractDispatchOrders(string customerNo) {
            object[] results = this.Invoke("GetCustomerContractDispatchOrders", new object[] {
                        customerNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerContractDispatchOrdersAsync(string customerNo) {
            this.GetCustomerContractDispatchOrdersAsync(customerNo, null);
        }
        
        /// <remarks/>
        public void GetCustomerContractDispatchOrdersAsync(string customerNo, object userState) {
            if ((this.GetCustomerContractDispatchOrdersOperationCompleted == null)) {
                this.GetCustomerContractDispatchOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerContractDispatchOrdersOperationCompleted);
            }
            this.InvokeAsync("GetCustomerContractDispatchOrders", new object[] {
                        customerNo}, this.GetCustomerContractDispatchOrdersOperationCompleted, userState);
        }
        
        private void OnGetCustomerContractDispatchOrdersOperationCompleted(object arg) {
            if ((this.GetCustomerContractDispatchOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerContractDispatchOrdersCompleted(this, new GetCustomerContractDispatchOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCustomerContractReceiptOrde" +
            "rs", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCustomerContractReceiptOrders_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCustomerContractReceiptOrders(string customerNo) {
            object[] results = this.Invoke("GetCustomerContractReceiptOrders", new object[] {
                        customerNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerContractReceiptOrdersAsync(string customerNo) {
            this.GetCustomerContractReceiptOrdersAsync(customerNo, null);
        }
        
        /// <remarks/>
        public void GetCustomerContractReceiptOrdersAsync(string customerNo, object userState) {
            if ((this.GetCustomerContractReceiptOrdersOperationCompleted == null)) {
                this.GetCustomerContractReceiptOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerContractReceiptOrdersOperationCompleted);
            }
            this.InvokeAsync("GetCustomerContractReceiptOrders", new object[] {
                        customerNo}, this.GetCustomerContractReceiptOrdersOperationCompleted, userState);
        }
        
        private void OnGetCustomerContractReceiptOrdersOperationCompleted(object arg) {
            if ((this.GetCustomerContractReceiptOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerContractReceiptOrdersCompleted(this, new GetCustomerContractReceiptOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCustomerContractReleaseOrde" +
            "rs", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCustomerContractReleaseOrders_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCustomerContractReleaseOrders(string customerNo) {
            object[] results = this.Invoke("GetCustomerContractReleaseOrders", new object[] {
                        customerNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerContractReleaseOrdersAsync(string customerNo) {
            this.GetCustomerContractReleaseOrdersAsync(customerNo, null);
        }
        
        /// <remarks/>
        public void GetCustomerContractReleaseOrdersAsync(string customerNo, object userState) {
            if ((this.GetCustomerContractReleaseOrdersOperationCompleted == null)) {
                this.GetCustomerContractReleaseOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerContractReleaseOrdersOperationCompleted);
            }
            this.InvokeAsync("GetCustomerContractReleaseOrders", new object[] {
                        customerNo}, this.GetCustomerContractReleaseOrdersOperationCompleted, userState);
        }
        
        private void OnGetCustomerContractReleaseOrdersOperationCompleted(object arg) {
            if ((this.GetCustomerContractReleaseOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerContractReleaseOrdersCompleted(this, new GetCustomerContractReleaseOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCustomerContractTransferOrd" +
            "ers", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCustomerContractTransferOrders_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCustomerContractTransferOrders(string customerNo) {
            object[] results = this.Invoke("GetCustomerContractTransferOrders", new object[] {
                        customerNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerContractTransferOrdersAsync(string customerNo) {
            this.GetCustomerContractTransferOrdersAsync(customerNo, null);
        }
        
        /// <remarks/>
        public void GetCustomerContractTransferOrdersAsync(string customerNo, object userState) {
            if ((this.GetCustomerContractTransferOrdersOperationCompleted == null)) {
                this.GetCustomerContractTransferOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerContractTransferOrdersOperationCompleted);
            }
            this.InvokeAsync("GetCustomerContractTransferOrders", new object[] {
                        customerNo}, this.GetCustomerContractTransferOrdersOperationCompleted, userState);
        }
        
        private void OnGetCustomerContractTransferOrdersOperationCompleted(object arg) {
            if ((this.GetCustomerContractTransferOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerContractTransferOrdersCompleted(this, new GetCustomerContractTransferOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCustomerEmail", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCustomerEmail_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCustomerEmail(string username) {
            object[] results = this.Invoke("GetCustomerEmail", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerEmailAsync(string username) {
            this.GetCustomerEmailAsync(username, null);
        }
        
        /// <remarks/>
        public void GetCustomerEmailAsync(string username, object userState) {
            if ((this.GetCustomerEmailOperationCompleted == null)) {
                this.GetCustomerEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerEmailOperationCompleted);
            }
            this.InvokeAsync("GetCustomerEmail", new object[] {
                        username}, this.GetCustomerEmailOperationCompleted, userState);
        }
        
        private void OnGetCustomerEmailOperationCompleted(object arg) {
            if ((this.GetCustomerEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerEmailCompleted(this, new GetCustomerEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCustomerProfileDetails", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCustomerProfileDetails_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCustomerProfileDetails(string username) {
            object[] results = this.Invoke("GetCustomerProfileDetails", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerProfileDetailsAsync(string username) {
            this.GetCustomerProfileDetailsAsync(username, null);
        }
        
        /// <remarks/>
        public void GetCustomerProfileDetailsAsync(string username, object userState) {
            if ((this.GetCustomerProfileDetailsOperationCompleted == null)) {
                this.GetCustomerProfileDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerProfileDetailsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerProfileDetails", new object[] {
                        username}, this.GetCustomerProfileDetailsOperationCompleted, userState);
        }
        
        private void OnGetCustomerProfileDetailsOperationCompleted(object arg) {
            if ((this.GetCustomerProfileDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerProfileDetailsCompleted(this, new GetCustomerProfileDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:UpdateCustomerAutoGenPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="UpdateCustomerAutoGenPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UpdateCustomerAutoGenPassword(string username, string genpass) {
            object[] results = this.Invoke("UpdateCustomerAutoGenPassword", new object[] {
                        username,
                        genpass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCustomerAutoGenPasswordAsync(string username, string genpass) {
            this.UpdateCustomerAutoGenPasswordAsync(username, genpass, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerAutoGenPasswordAsync(string username, string genpass, object userState) {
            if ((this.UpdateCustomerAutoGenPasswordOperationCompleted == null)) {
                this.UpdateCustomerAutoGenPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerAutoGenPasswordOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomerAutoGenPassword", new object[] {
                        username,
                        genpass}, this.UpdateCustomerAutoGenPasswordOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerAutoGenPasswordOperationCompleted(object arg) {
            if ((this.UpdateCustomerAutoGenPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerAutoGenPasswordCompleted(this, new UpdateCustomerAutoGenPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:UpdateCustomerPassword", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="UpdateCustomerPassword_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string UpdateCustomerPassword(string username, string password) {
            object[] results = this.Invoke("UpdateCustomerPassword", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCustomerPasswordAsync(string username, string password) {
            this.UpdateCustomerPasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerPasswordAsync(string username, string password, object userState) {
            if ((this.UpdateCustomerPasswordOperationCompleted == null)) {
                this.UpdateCustomerPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerPasswordOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomerPassword", new object[] {
                        username,
                        password}, this.UpdateCustomerPasswordOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerPasswordOperationCompleted(object arg) {
            if ((this.UpdateCustomerPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerPasswordCompleted(this, new UpdateCustomerPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckCustomerLoginCompletedEventHandler(object sender, CheckCustomerLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCustomerLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCustomerLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckValidCustomerNoCompletedEventHandler(object sender, CheckValidCustomerNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckValidCustomerNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckValidCustomerNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GenerateReleaseOrderReportCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GenerateWarehouseReceiptCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCMAProductLedgerCompletedEventHandler(object sender, GetCMAProductLedgerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCMAProductLedgerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCMAProductLedgerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetClientContractsCompletedEventHandler(object sender, GetClientContractsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientContractsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientContractsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetContractPartiesCompletedEventHandler(object sender, GetContractPartiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContractPartiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContractPartiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetContractProductsCompletedEventHandler(object sender, GetContractProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContractProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContractProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetContractStorageCompletedEventHandler(object sender, GetContractStorageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContractStorageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContractStorageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCustomerContractDispatchOrdersCompletedEventHandler(object sender, GetCustomerContractDispatchOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerContractDispatchOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerContractDispatchOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCustomerContractReceiptOrdersCompletedEventHandler(object sender, GetCustomerContractReceiptOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerContractReceiptOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerContractReceiptOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCustomerContractReleaseOrdersCompletedEventHandler(object sender, GetCustomerContractReleaseOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerContractReleaseOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerContractReleaseOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCustomerContractTransferOrdersCompletedEventHandler(object sender, GetCustomerContractTransferOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerContractTransferOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerContractTransferOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCustomerEmailCompletedEventHandler(object sender, GetCustomerEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCustomerProfileDetailsCompletedEventHandler(object sender, GetCustomerProfileDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerProfileDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerProfileDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateCustomerAutoGenPasswordCompletedEventHandler(object sender, UpdateCustomerAutoGenPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCustomerAutoGenPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCustomerAutoGenPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateCustomerPasswordCompletedEventHandler(object sender, UpdateCustomerPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCustomerPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCustomerPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591