//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OperationsPortal.NAVWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Operations_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/Operations")]
    public partial class Operations : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckCustomerLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckValidCustomerNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateWarehouseReceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerProfileDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Operations() {
            this.Url = global::OperationsPortal.Properties.Settings.Default.OperationsPortal_NAVWS_OperationsPortal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckCustomerLoginCompletedEventHandler CheckCustomerLoginCompleted;
        
        /// <remarks/>
        public event CheckValidCustomerNoCompletedEventHandler CheckValidCustomerNoCompleted;
        
        /// <remarks/>
        public event GenerateWarehouseReceiptCompletedEventHandler GenerateWarehouseReceiptCompleted;
        
        /// <remarks/>
        public event GetCustomerProfileDetailsCompletedEventHandler GetCustomerProfileDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:CheckCustomerLogin", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="CheckCustomerLogin_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CheckCustomerLogin(string username, string userpassword) {
            object[] results = this.Invoke("CheckCustomerLogin", new object[] {
                        username,
                        userpassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckCustomerLoginAsync(string username, string userpassword) {
            this.CheckCustomerLoginAsync(username, userpassword, null);
        }
        
        /// <remarks/>
        public void CheckCustomerLoginAsync(string username, string userpassword, object userState) {
            if ((this.CheckCustomerLoginOperationCompleted == null)) {
                this.CheckCustomerLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCustomerLoginOperationCompleted);
            }
            this.InvokeAsync("CheckCustomerLogin", new object[] {
                        username,
                        userpassword}, this.CheckCustomerLoginOperationCompleted, userState);
        }
        
        private void OnCheckCustomerLoginOperationCompleted(object arg) {
            if ((this.CheckCustomerLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCustomerLoginCompleted(this, new CheckCustomerLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:CheckValidCustomerNo", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="CheckValidCustomerNo_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckValidCustomerNo(string username) {
            object[] results = this.Invoke("CheckValidCustomerNo", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckValidCustomerNoAsync(string username) {
            this.CheckValidCustomerNoAsync(username, null);
        }
        
        /// <remarks/>
        public void CheckValidCustomerNoAsync(string username, object userState) {
            if ((this.CheckValidCustomerNoOperationCompleted == null)) {
                this.CheckValidCustomerNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckValidCustomerNoOperationCompleted);
            }
            this.InvokeAsync("CheckValidCustomerNo", new object[] {
                        username}, this.CheckValidCustomerNoOperationCompleted, userState);
        }
        
        private void OnCheckValidCustomerNoOperationCompleted(object arg) {
            if ((this.CheckValidCustomerNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckValidCustomerNoCompleted(this, new CheckValidCustomerNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GenerateWarehouseReceipt", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GenerateWarehouseReceipt_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateWarehouseReceipt(string path, string fileName, string pensionerNo) {
            this.Invoke("GenerateWarehouseReceipt", new object[] {
                        path,
                        fileName,
                        pensionerNo});
        }
        
        /// <remarks/>
        public void GenerateWarehouseReceiptAsync(string path, string fileName, string pensionerNo) {
            this.GenerateWarehouseReceiptAsync(path, fileName, pensionerNo, null);
        }
        
        /// <remarks/>
        public void GenerateWarehouseReceiptAsync(string path, string fileName, string pensionerNo, object userState) {
            if ((this.GenerateWarehouseReceiptOperationCompleted == null)) {
                this.GenerateWarehouseReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateWarehouseReceiptOperationCompleted);
            }
            this.InvokeAsync("GenerateWarehouseReceipt", new object[] {
                        path,
                        fileName,
                        pensionerNo}, this.GenerateWarehouseReceiptOperationCompleted, userState);
        }
        
        private void OnGenerateWarehouseReceiptOperationCompleted(object arg) {
            if ((this.GenerateWarehouseReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateWarehouseReceiptCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Operations:GetCustomerProfileDetails", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", ResponseElementName="GetCustomerProfileDetails_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/Operations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetCustomerProfileDetails(string username) {
            object[] results = this.Invoke("GetCustomerProfileDetails", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerProfileDetailsAsync(string username) {
            this.GetCustomerProfileDetailsAsync(username, null);
        }
        
        /// <remarks/>
        public void GetCustomerProfileDetailsAsync(string username, object userState) {
            if ((this.GetCustomerProfileDetailsOperationCompleted == null)) {
                this.GetCustomerProfileDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerProfileDetailsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerProfileDetails", new object[] {
                        username}, this.GetCustomerProfileDetailsOperationCompleted, userState);
        }
        
        private void OnGetCustomerProfileDetailsOperationCompleted(object arg) {
            if ((this.GetCustomerProfileDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerProfileDetailsCompleted(this, new GetCustomerProfileDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CheckCustomerLoginCompletedEventHandler(object sender, CheckCustomerLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCustomerLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCustomerLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CheckValidCustomerNoCompletedEventHandler(object sender, CheckValidCustomerNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckValidCustomerNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckValidCustomerNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GenerateWarehouseReceiptCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCustomerProfileDetailsCompletedEventHandler(object sender, GetCustomerProfileDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerProfileDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerProfileDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591